In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
techSalariesDf = pd.read_csv("/Users/alliborland/Desktop/Visual Studio/FinalProject2302/edited_salaries.csv")


selected_locations = ['Seattle, WA', 'San Francisco, CA', 'New York, NY', 'Redmond, WA', 'Mountain View, CA']

techSalariesDf = techSalariesDf[techSalariesDf['location'].isin(selected_locations)]

techSalariesDf

title  totalyearlycompensation  yearsofexperience  \
0      Software Engineer                   100000                5.0   
1      Software Engineer                   157000                5.0   
2      Software Engineer                   208000                8.5   
3      Software Engineer                   156000                4.0   
4      Software Engineer                   120000                3.0   
...                  ...                      ...                ...   
41225  Software Engineer                   170000                2.0   
41226  Software Engineer                   327000               10.0   
41227  Software Engineer                   237000                2.0   
41228  Software Engineer                   220000               14.0   
41229  Software Engineer                   280000                8.0   

                location experience_category  
0      San Francisco, CA                 4-6  
1      Mountain View, CA                 4-6  
2            Seattle, WA                 7-9  
3            Seattle, WA                 4-6  
4            Redmond, WA                 0-3  
...                  ...                 ...  
41225        Seattle, WA                 0-3  
41226        Seattle, WA               10-19  
41227        Redmond, WA                 0-3  
41228        Seattle, WA               10-19  
41229  San Francisco, CA                 7-9  

[16297 rows x 5 columns]

## Linear Regression

In [ ]:
techSalariesDf = pd.read_csv("/Users/alliborland/Desktop/Visual Studio/FinalProject2302/edited_salaries.csv")

selected_locations = ['Seattle, WA', 'San Francisco, CA', 'New York, NY', 'Redmond, WA', 'Mountain View, CA']
techSalariesDf = techSalariesDf[techSalariesDf['location'].isin(selected_locations)]

techSalariesDf = pd.get_dummies(techSalariesDf, columns=['location'])

X = techSalariesDf[['yearsofexperience', 'location_Seattle, WA', 'location_San Francisco, CA', 'location_New York, NY', 'location_Redmond, WA', 'location_Mountain View, CA']]
y = techSalariesDf['totalyearlycompensation']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)


Mean Squared Error: 10274018813.729246
Coefficients: [ 11526.63795765  -8229.83650775  33288.53099864 -10982.26548817
 -53539.68796645  39463.25896373]


what this means:

The coefficients represent the estimated effect of each feature on the total yearly compensation:

For every additional year of experience, the total yearly compensation is estimated to increase by approximately $11,526.64.
Being located in Seattle, WA seems to be associated with a decrease in total yearly compensation by approximately $8,229.84.
Being located in San Francisco, CA appears to be associated with an increase in total yearly compensation by approximately $33,288.53.
Being located in New York, NY appears to be associated with a decrease in total yearly compensation by approximately $10,982.27.
Being located in Redmond, WA appears to be associated with a significant decrease in total yearly compensation by approximately $53,539.69.
Being located in Mountain View, CA appears to be associated with an increase in total yearly compensation by approximately $39,463.26.

In [ ]:
techSalariesDf = pd.read_csv("/Users/alliborland/Desktop/Visual Studio/FinalProject2302/edited_salaries.csv")

X = techSalariesDf[['yearsofexperience']]
y = techSalariesDf['totalyearlycompensation']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

print("Coefficients:", model.coef_)

Mean Squared Error: 12332463315.888311
Coefficients: [9234.15081157]


Mean Squared Error (MSE): The MSE value of approximately 12.33 billion indicates the average squared difference between the actual total yearly compensation values and the predicted values by your regression model. Since MSE is a measure of the model's accuracy, lower values of MSE indicate better fit, implying that the model's predictions are closer to the actual values on average.

Coefficients: The coefficient of approximately 9234.15 represents the estimated effect of years of experience on total yearly compensation. Specifically, it indicates how much the total yearly compensation is estimated to increase for every additional year of experience, holding other factors constant. In this case, the coefficient suggests that, on average, total yearly compensation increases by approximately $9234.15 for each additional year of experience.

High MSE: A high MSE indicates that the model's predictions are far from the actual values on average, suggesting that the model might not be capturing the underlying patterns in the data effectively. In such cases, it might be necessary to investigate potential issues with the model's features, assumptions, or complexity.

## Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

decision_tree = DecisionTreeRegressor(random_state=42)

decision_tree.fit(X_train, y_train)

y_pred_tree = decision_tree.predict(X_test)

mse_tree = mean_squared_error(y_test, y_pred_tree)
print("Decision Tree Mean Squared Error:", mse_tree)

print("Coefficients:", model.coef_)

Decision Tree Mean Squared Error: 12261217415.057077


## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Initialize the Random Forest regression model
random_forest = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the Random Forest model
random_forest.fit(X_train, y_train)

# Predict total yearly compensation on the testing set
y_pred_rf = random_forest.predict(X_test)

# Evaluate the Random Forest model
mse_rf = mean_squared_error(y_test, y_pred_rf)
print("Random Forest Mean Squared Error:", mse_rf)

Random Forest Mean Squared Error: 12246419927.949364


In [ ]:
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42)
}

param_grid = {
    "Linear Regression": {},
    "Decision Tree": {"max_depth": [None, 5, 10]},
    "Random Forest": {"n_estimators": [50, 100, 200]},
    "Gradient Boosting": {"n_estimators": [50, 100, 200], "learning_rate": [0.05, 0.1, 0.2]}
}

results = {}
for name, model in models.items():
    grid_search = GridSearchCV(model, param_grid[name], cv=KFold(n_splits=5, shuffle=True, random_state=42), scoring='neg_mean_squared_error')
    grid_search.fit(X_train, y_train)
    results[name] = grid_search.best_estimator_

for name, model in results.items():
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    print(f"{name} Mean Squared Error: {mse}")

Linear Regression Mean Squared Error: 12332463315.888311
Decision Tree Mean Squared Error: 12161487859.933638
Random Forest Mean Squared Error: 12239577951.9591
Gradient Boosting Mean Squared Error: 12170267129.42855


In [ ]:
from sklearn.pipeline import make_pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    "SVR": SVR(),
    "KNN Regression": KNeighborsRegressor(),
    "ElasticNet Regression": ElasticNet(),
    "Bayesian Ridge Regression": BayesianRidge(),
    "Gaussian Process Regression": GaussianProcessRegressor(kernel=RBF()),
    "MLP Regression": MLPRegressor()
}

for name, model in models.items():
    if name in ["SVR", "ElasticNet Regression", "MLP Regression"]:
        pipeline = make_pipeline(StandardScaler(), model)
        pipeline.fit(X_train, y_train)
        y_pred = pipeline.predict(X_test)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    print(f"{name} Mean Squared Error: {mse}")

NameError: name 'SVR' is not defined

Interpretation: While the MSE values may seem high, especially in absolute terms, their interpretation should consider the context of the problem and the scale of the target variable. MSE represents the average squared difference between predicted and actual values, so higher MSE values suggest larger discrepancies between predictions and actual outcomes on average.

SOOO the best model is decision trees which we already did

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6b1639a5-1f60-4e70-b39d-b83cfcee6430' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>